### PR TITLE
SystemdJournalDecoder

### PR DESCRIPTION
**Pull request by nathwill**
add a basic decoder for json-formatted systemd journal entries

### CODE REVIEW

**Comment by nathwill** [comment]
mmmm.... nm, going to work on this as a sandbox input instead.

**Comment by bbinet** [comment]
@nathwill I'm also interested by a systemd journal input sandbox: have you continued to work on this? Would you have anything to share?

**Comment by nathwill** [comment]
@bbinet no, unfortunately i haven't found the time to make a journal-specific sandbox input; for now something like described in https://github.com/mozilla-services/heka/issues/358#issuecomment-191462517 works well enough.

**Comment by bbinet** [comment]
Thanks for you answer @nathwill 
I will try to work on it in the near future.

**Pull request closed without merging**
