### PR TITLE
Update to Sarama 1.5.0, add `git_clone_to_path` to build, use it

### PR DESCRIPTION
**Pull request by rafrombrc**
to clone Sarama into its Shopify package path.

### CODE REVIEW

**Comment by whd** [comment]
This has been tested pretty heavily and appears to work well :+1:. I think it's ready for code review and merging (after the merge conflict is fixed).

**Comment by andremedeiros** [comment]
@rafrombrc this is actually good news. We've just release 1.6, which has some CRC32 performance increases.

Shall I get this branch up to date with Sarama 1.6? I wouldn't mind taking the "burden" of keeping that up to date either.

**Comment by rafrombrc** [comment]
Yes, I'd love to have your help keeping up w/ the latest Sarama changes! Unfortunately, I think moving from Sarama 1.5 to Sarama 1.6 will have to be a separate PR, though, since this particular code base has already been extensively load tested in our deployment environment, and I don't want to rock that boat by changing the underlying code out from under it.

Also, you'll note that I'm still using a fork of Sarama. The only changes in my fork are related to test code; we wrote tests for Heka that make use of Sarama'a MockBroker, back when that was public and available for import. That has since been made private, and I didn't have the time to reimplement our testing infrastructure, so I forked the repo and made the mock stuff public. There are no changes of any sort to the code that actually runs in Heka, however, so using the stock Sarama should work until you try to run the tests.

**Comment by andremedeiros** [comment]
Interesting.

I've already rebased this branch with the latest dev and Sarama 1.6. I actually noticed some improvements on performance. 

I'll touch base with the maintainers to see if we can make those public again. In the meantime, should I send you PRs for this?

**Comment by rafrombrc** [comment]
@andremedeiros Okay, this has now been merged back to Heka's main dev branch. I'd love to get a PR from you upgrading to Sarama 1.6. The merged code is using a SHA from the `versions/1.5` branch in [my fork](https://github.com/rafrombrc/sarama/tree/versions/1.5) of Sarama. As mentioned above, this is identical to the v1.5.0 release tag except that the mocks that Sarama defines [have been made public](https://github.com/Shopify/sarama/compare/v1.5.0...rafrombrc:versions/1.5).

Similarly, I've created 1 `versions/1.6` branch, which I cut from `versions/1.5` and then merged in the upstream v1.6.0 tag. I've verified that this matches the 1.6 release, [except for the public mocks](https://github.com/Shopify/sarama/compare/v1.6.0...rafrombrc:versions/1.6). In the Heka build, you can refer to the latest SHA on that branch to upgrade Heka to using Sarama 1.6.

I'd love for the mocks to be made public, but I understand why they became private in the first place. It's pretty ugly to have a bunch of test-related code cluttering up the public APIs. In Heka we've worked around this in a few places by making mocks available in a [separate package](https://github.com/mozilla-services/heka/blob/dev/plugins/payload/multidecoder_test.go#L33). (Note you won't find the `pipelinemock` package in the source tree, since it's generated by our build.) This has some issues, though, b/c of course you can't get at package-private code from an external package. Not sure what the best resolution is.

**Comment by andremedeiros** [comment]
I'll figure something out! :heart:

**Pull request merged**
