### PR TITLE
Allow to set hostname from UDP remote

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
I don't know enough of Go, and get:
```
heka/plugins/udp/udp_input.go:125: impossible type assertion:
	net.UDPConn does not implement net.Conn (Close method has pointer receiver)
```

**Comment by sathieu** [comment]
At least, now it compiles. Will test soon.

**Comment by sathieu** [comment]
Verified. it now works for me.

**Comment by rafrombrc** [comment]
This looks great. I'd love to have this land in 0.10.0... would you mind closing this PR and re-opening it against the `versions/0.10` branch? Also would be lovely to have a note in the `Features` section for 0.10.0 in the CHANGES.txt changelog. Thanks!

**Comment by rafrombrc** [comment]
Okay, cherry-picked this, added changelog entry, and merged to versions/0.10 in 51eab33391cdc11cc12dc867c93ef4602088ccb2.

**Pull request closed without merging**
