### PR TITLE
Support sd_notify (from systemd) for reliable service status

### PR DESCRIPTION
**Pull request by sathieu**
See http://www.freedesktop.org/software/systemd/man/sd_notify.html

### CODE REVIEW

**Comment by sathieu** [comment]
This is an interim patch.

As better integration would include
* systemd-journal input (#358),
* sd_notify (this one)
* socket-activation (LISTEN_PID/LISTEN_FDS)
* journal output

Maybe using https://github.com/coreos/go-systemd would be a better path than rewriting everything. What do you think? (even if journal reading is not done yet: https://github.com/coreos/go-systemd/issues/70)

**Comment by trink** [comment]
See: https://github.com/daurnimator/lua-systemd

**Comment by sathieu** [comment]
Thanks @trink, but how to do socket activation of an UdpInput (written in go) from a lua library?

**Comment by trink** [comment]
I am not sure what your use case is or even why you would need/want to split it up between Go/Lua

**Comment by sathieu** [comment]
I need to:
*  have a journal input,
* socket-ativate port 514 (udp and tcp), to loose less syslog messages
* Have Type=notify, to correctly handle hekad availibility
* (optionnaly) have watchdog

I don't care if this is done in lua or Go, but point 2 and 3 probably need to be in Go as they are in heka core.

**Comment by sathieu** [comment]
Closing PR as Heka is a dead projet...

**Pull request closed without merging**
