### PR TITLE
Nginx error log have time

### PR DESCRIPTION
**Pull request by vlastv**

### CODE REVIEW

**Comment by trink** [comment]
Let's just fix the grammar to put it in Timestamp.

**Comment by vlastv** [comment]
I can fix grammar, but then need to correct all decoders apache and nginx.
Do it?

**Comment by vlastv** [comment]
Grammar is described in a different repository, respectively, will be broken backward compatibility

**Comment by trink** [comment]
That grammar is specific to nginx. As for breaking compatibility it will now work as expected and it clearly hasn't been used much (so I am not that concerned)

**Comment by vlastv** [comment]
If the grammar should not be parsed into the heka schema then the PR is complete.
Otherwise, I have to change the grammar:
- time -> Timestamp
- pid -> Pid

Change the grammar?

**Comment by trink** [comment]
We are talking about the nginx_error_grammar only: Pid is already correct and the Timestamp change we already discussed (that should be changed).

**Pull request closed without merging**
