### PR TITLE
Make StatAccumInput Plugin Support Multi percent_threshold values

### PR DESCRIPTION
**Pull request by i19**
StatsD support it . So i made it happen in heka too. 
And this should help developer to know the how the trend really goes .

### CODE REVIEW

**Comment by i19** [comment]
The configuration should be like this

```
[StatAccumInput]
percent_threshold = [90, 95, 99]
delete_idle_stats = false
ticker_interval = 10]
```

**Comment by rafrombrc** [comment]
This looks great, thanks! A couple more details need to be handled before it can be merged, however. First, we need an entry in the `Backwards Incompatibilities` section for version 0.11.0 of the CHANGES.txt changelog. Second, the documentation needs to be updated in the stataccum.rst file.

**Comment by i19** [comment]
The docs has been updated, please review .

**Comment by rafrombrc** [comment]
Docs looks good, thanks! Unfortunately, however, I ran the tests against your branch and one of the stat accumulator tests is now failing. Sorry for not checking that before... :P

**Comment by i19** [comment]
That's a pity. 
Could you show me the testing result , or testing case, or testing method.
I didn't find the document about running the testing in the doc .

**Comment by rafrombrc** [comment]
You can run `ctest` from the repo checkout directory, or `make test` from the build folder if you've already set up the environment using `. env.sh`. If the environment is set up, you can also use the go tool to just run specific package tests, e.g. `go test -v github.com/mozilla-services/heka/pipeline`.

**Comment by i19** [comment]
I checked the testing case . The error is caused by the default value i set for the percentValue list .
I removed it !
And in the dev branch, when calculate the percent value, it has an logic that would judge if the timing data is bigger than 1, but if i have multi percent setting, then it would be unreasonable, and it would be conflict try to handle that situation. So i remove the judge, ether.

**Comment by tclh123** [comment]
:beers:

**Pull request merged**
