### PR TITLE
DockerLogInput: add new `fields_from_env`

### PR DESCRIPTION
**Pull request by mattrobenolt**
Example:

```toml
[DockerLogInput]
fields_from_env = [ "FOO", "BAR" ]
```

### CODE REVIEW

**Comment by rafrombrc** [comment]
This looks good, and despite the (broken, and now deactivated, sadly) Travis failures the tests are all passing. Before I can merge, however, the docker_log.rst documentation file needs to be updated to describe the new setting's behavior, and an entry needs to be added to the CHANGES.txt changelog. Thanks!

**Comment by intjonathan** [comment]
+1 we would LOVE to have this.

**Comment by mattrobenolt** [comment]
I apologize, got a little backlogged. Let me button this up today. :)

**Comment by mattrobenolt** [comment]
@rafrombrc Updated to add docs/changelog.

**Pull request merged**
