### PR TITLE
Update lua_sandbox, add max-depth and sep-char to JsonDecoder

### PR DESCRIPTION
**Pull request by nathwill**

### CODE REVIEW

**Comment by rafrombrc** [comment]
Closes #1809.

**Comment by nathwill** [comment]
@rafrombrc i'm not sure why exactly, but there does seem to be something weird with the nesting... the test matches experimental results but `GetFieldValue("nested1-field")` keeps getting `nil`, so those 2 tests are failing :crying_cat_face:, still digging, but if you have any pointers, i'd appreciate it.

**Comment by rafrombrc** [comment]
Test was failing b/c sandbox config expects number values to be type int64 or float64, unspecified is type int. I fixed this, changed the name of the setting from `separator_char` to `separator`, and added a changelog entry. Merging now. Thanks for tackling this!

**Comment by nathwill** [comment]
awesome, thanks Rob!

**Pull request merged**
