### PR TITLE
Added help parameter to hekad and changed loading of config parameter. Fixes #1239

### LINKED ISSUE #1239: /etc/hekad.toml not used by default on 0.8.0 / os: debian
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux
heka 0.8.0

hekad doesn't use /etc/hekad.toml by default as stated in the man page... You have to specify -config /etc/hekad.toml in order to startup properly.

### PR DESCRIPTION
**Pull request by 4r9h**
It slightly changes behaviour of hekad so i think it needs @rafrombrc approval.

### CODE REVIEW

**Comment by rafrombrc** [comment]
I'm confused. Go gives us `-help` and `-h` for free, so this doesn't seem to add any new features. I also don't see how this resolves #1239, since typing a bare `hekad` will still fail as before, yes?

**Comment by rafrombrc** [comment]
Ooops, my bad, I misread the diff, now I see that you removed the "no flags" check, this *does* resolve #1239. But the other part of my comment still stands; we get `-help` for free, so we just need to remove the entire `if flag.NFlag()` clause.

Also, please add a bug fix note to CHANGES.txt. :)

**Comment by 4r9h** [comment]
Okay, i didn't know about "-h" :D i just assumed it must be done
"manually". I'll load fix in next couple of hours.

On Wed, Jan 21, 2015 at 7:32 PM, Rob Miller <notifications@github.com>
wrote:

> Ooops, my bad, I misread the diff, now I see that you removed the "no
> flags" check, this *does* resolve #1239
> <https://github.com/mozilla-services/heka/issues/1239>. But the other
> part of my comment still stands; we get -help for free, so we just need
> to remove the entire if flag.NFlag() clause.
>
> Also, please add a bug fix note to CHANGES.txt. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla-services/heka/pull/1283#issuecomment-70893711>
> .
>



-- 
jarek@reijutsu:~$ fortune
You have Egyptian flu: you're going to be a mummy.
jarek@reijutsu:~$ fortune
You now have Asian Flu.

**Comment by 4r9h** [comment]
@rafrombrc okay, i've updated  pull request.

**Pull request merged**
