### PR TITLE
Enable AMQP input to use a read-only user

### LINKED ISSUE #1314: AMQP input binding to readonly exchange
I'm trying to set up an AMQP input to an exchange that I only have read permissions to.  It seems the default behaviour is to declare an exchange, which requires readwrite permissions.  It is possible to simply bind to the exchange, if so, its not obvious how to do this from the documentation.

This is my current configuration:
```
[AMQPInput]
url = "amqp://user:password@amqp.company.com/VHOST"
exchange = "MyExchange"
exchange_type = "topic"
exchange_durability = true
exchange_auto_delete =  false
routing_key = "#"
queue = "test"
decoder = "json_decoder"
```

Thanks
Alex

### PR DESCRIPTION
**Pull request by mattrco**
This adds a configuration option, ReadOnly, to AMQP input to
allow users which only have read access to connect to a queue.

The exchange, queue, and binding must be declared prior to
starting heka with a read-only user.

The config option defaults to false. Fixes #1314.

### CODE REVIEW

**Comment by mattrco** [comment]
(Happy to update docs for this when/if it's merged)

**Comment by ioc32** [comment]
Cannot comment on the code (go is not my strong suit) but the feature is very nice. It allows us to exert tighter control over the data pipeline.

Looking forward to see progress here! I can give a hand too if you need the docs updated.

**Comment by rafrombrc** [comment]
This looks fine, but the docs will need to be added *before* we can merge it to dev. Also we'll want to add an entry to the "bug handling" section for 0.9 in the CHANGES.txt changelog file. Thanks!

**Comment by mattrco** [comment]
Thanks for the review @rafrombrc, I've added docs.

**Pull request merged**
