### PR TITLE
Moved MAX_MESSAGE_SIZE to configuration variables. Fixes #1208

### LINKED ISSUE #1208: Make the maximum message size a configuration option
... instead of a compile time option.

### PR DESCRIPTION
**Pull request by 4r9h**

### CODE REVIEW

**Comment by ecnahc515** [comment]
Any reason this is using `uint32` and then converting to `uint64` instead of just using a `uint64` as the type from the beginning? I imagine the difference in types could be related to the test failures.

**Comment by 4r9h** [comment]
Hm, strange - tests somehow passed locally on my machine. I must forgot to
recompile (?). I'll fix this later, thx for notice!

On Mon, Feb 16, 2015 at 3:34 AM, Chance Zibolski <notifications@github.com>
wrote:

> Any reason this is using uint32 and then converting to uint64 instead of
> just using a uint64 as the type from the beginning? I imagine the
> difference in types could be related to the test failures.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla-services/heka/pull/1339#issuecomment-74452718>
> .
>



-- 
jarek@reijutsu:~$ fortune
You have Egyptian flu: you're going to be a mummy.
jarek@reijutsu:~$ fortune
You now have Asian Flu.

**Comment by rafrombrc** [comment]
I fixed the tests, made one small tweak, and merged this to dev. Sorta hosed the merge / rebase, though, so it didn't close this automatically.

**Comment by 4r9h** [comment]
@rafrombrc thx... sorry for such delays - i have some issues in my private life and just caused me to stop coding.

**Pull request closed without merging**
