### PR TITLE
Add Basic Auth and API key authentication to HttpListenInput #1533

### PR DESCRIPTION
**Pull request by michaelgibson**
https://github.com/mozilla-services/heka/issues/1533

### CODE REVIEW

**Comment by rafrombrc** [comment]
Travis build is failing.

**Comment by michaelgibson** [comment]
bah! 
looks like BasicAuth is a 1.4 thing: http://golang.org/pkg/net/http/#Request.BasicAuth
Any idea when Heka will be worthy of the new version?

**Comment by rafrombrc** [comment]
I'm up for making 0.10, targeter for release by the end of this month, require Go 1.4 or greater.

**Comment by michaelgibson** [comment]
Cool! 
PR for https://github.com/mozilla-services/heka/issues/1543 on it's way.

**Pull request merged**
